import { Metadata } from "next";
import Head from "next/head";
import Image from "next/image";
import "./styles/global.css";
import utilStyles from "./styles/utils.module.css";
import styles from "./layout.module.css";

export const metadata: Metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export const siteTitle = "Next.js Sample Website";
const name = "Josh K";

type Props = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: Props): JSX.Element {
  return (
    <html lang="en">
      <body>
        <div className={styles.container}>
          <Head>
            <link rel="icon" href="/favicon.ico" />
            {/* <meta
              name="description"
              content="Learn how to build a personal website using Next.js"
            /> */}
            <meta
              property="og:image"
              content={`https://og-image.vercel.app/${encodeURI(
                siteTitle,
              )}.png?theme=light&md=0&fontSize=75px&images=https%3A%2F%2Fassets.vercel.com%2Fimage%2Fupload%2Ffront%2Fassets%2Fdesign%2Fnextjs-black-logo.svg`}
            />
            <meta name="og:title" content={siteTitle} />
            <meta name="twitter:card" content="summary_large_image" />
          </Head>
          <header className={styles.header}>
            <Image
              priority
              src="/images/profile.jpg"
              className={utilStyles.borderCircle}
              height={144}
              width={144}
              alt=""
            />
            <h1 className={utilStyles.heading2Xl}>{name}</h1>
          </header>
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
